app/urls.py
from django.urls import path

from app.views import (
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    complete_add_to_task_view, complete_delete_from_task_view
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "<int:pk>/complete_add_to_task_view/",
        complete_add_to_task_view,
        name="complete-add-to-task"
    ),
    path(
        "<int:pk>/delete-user-from-drivers/",
        complete_delete_from_task_view,
        name="complete-delete-from-task"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "app"

todo_list_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255, blank=False, null=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_deadline = models.DateTimeField(blank=True, null=True)
    task_is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return f"{self.content} ({self.task_is_done})"

    class Meta:
        ordering = ["task_is_done", "-date_created"]

app/forms.py
from django import forms

from app.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from app.forms import TaskForm
from app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task-list")


def complete_add_to_task_view(request, pk):
    task = Task.objects.get(pk=pk)
    task.task_is_done = True
    task.save()
    return HttpResponseRedirect(reverse("app:task-list"))


def complete_delete_from_task_view(request, pk):
    task = Task.objects.get(pk=pk)
    task.task_is_done = False
    task.save()
    return HttpResponseRedirect(reverse("app:task-list"))


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("app:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("app:tag-list")

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}
   <title>Delete tag</title>
{% endblock %}

{% block content %}
    <h1>Delete tag</h1>
    <hr>
    <p>Are you sure you want to delete tag: <strong>"{{ tag.name }}"</strong></p>

    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" value="Yes, delete" class="btn btn-primary">
        <a href="{% url 'app:tag-list' %}" class="btn btn-primary">No</a>
    </form>
{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title>{{ object|yesno:"Update, Create" }} tag</title>
{% endblock %}

{% block content %}
    <h1> {{ object|yesno:"Update, Create" }} tag</h1>
    <hr>
    <form action="" method="post" novalidate >
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Tags
        <a style="float: right" class="btn btn-primary" href="{% url 'app:tag-create' %}">Add</a>
    </h1>
    {% if tag_list %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for tag in tag_list %}
          <tr>
            <td>
                {{ tag.name }}
            </td>
            <td>
                <a class="btn btn-secondary" href="{% url 'app:tag-update' pk=tag.id %}"> Update </a>
            </td>
            <td>
                <a class="btn btn-secondary" href="{% url 'app:tag-delete' pk=tag.id %}"> Delete </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
        <p>There are no tags in the database.</p>
    {% endif %}
{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}
   <title>Delete task</title>
{% endblock %}

{% block content %}
    <h1>Delete task</h1>
    <hr>
    <p>Are you sure you want to delete task: <strong>"{{ task.content }}"</strong></p>

    <form action="" method="post">
        {% csrf_token %}

        <input type="submit" value="Yes, delete" class="btn btn-primary">
        <a href="{% url 'app:task-list' %}" class="btn btn-primary">No</a>
    </form>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
   <title>{{ object|yesno:"Update, Create" }} task</title>
{% endblock %}

{% block content %}
    <h1> {{ object|yesno:"Update, Create" }} task</h1>
    <hr>
    <form action="" method="post" novalidate >
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/app/task_list.html
{% extends "base.html" %}
{% block content %}
    <h1>TODO list
        <a style="float: right" class="btn btn-primary" href="{% url 'app:task-create' %}">Add</a>
    </h1>
    <hr>
    {% if task_list %}
        {% for task in task_list %}
            <p>
                <span class="text-task">{{ task.content }}</span>
                {% if task.task_is_done %}
                    <span class="text-green">Done</span>
                    <a style="float: right" href="{% url 'app:complete-delete-from-task' pk=task.id %}" class="btn btn-primary">Undo</a>
                {% else %}
                    <span class="text-red">Not done</span>
                    <a style="float: right" href="{% url 'app:complete-add-to-task' pk=task.id %}" class="btn btn-primary">Complete</a>
                {% endif %}
            </p>
            <p>
                <span>Created: {{ task.date_created }}</span>
                {% if task.date_deadline %}
                    <span class="text-deadline"> Deadline: {{ task.date_deadline }}</span>
                {% endif %}
            <p>
                <span class="text-tag"> Tags: {% for tag in task.tags.all %} {{ tag.name }} {% endfor %} </span>
                <a class="btn btn-secondary" href="{% url 'app:task-update' pk=task.id %}">Update</a>
                <a class="btn btn-secondary" href="{% url 'app:task-delete' pk=task.id %}">Delete</a>
            </p>
            <hr>
        {% endfor %}
    {% else %}
        <p>There are no tasks in the database.</p>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'app:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'app:tag-list' %}">Tags</a></li>
</ul>